# membridge.pyi

def create_memory(memory_name: str) -> bool: ...
def remove_memory(memory_name: str) -> bool: ...
def read_memory(memory_name: str) -> bytes: ...
def write_memory(memory_name: str, value: bytes) -> bool: ...

def create_function(memory_name: str, function: callable) -> bool: ...
def remove_function(memory_name: str) -> int: ...
def call_function(memory_name: str, args: tuple) -> bool: ...

