# pybytes.pyi

def from_single_value(value: any, datatype: str) -> bytes: ...
def to_single_value(bytes_obj: bytes, datatype: str) -> any: ...
def from_value(value: any) -> bytes: ...
def to_value(bytes_obj: bytes) -> any: ...

